### YamlMime:QSharpNamespace
functions: []
name: Microsoft.Quantum.Environment
newtypes: []
operations:
- summary: Zwraca liczbę qubits, które są obecnie dostępne do zażyczania.
  uid: Microsoft.Quantum.Environment.GetQubitsAvailableToBorrow
- summary: Zwraca liczbę qubits, która jest obecnie dostępna do użycia.
  uid: Microsoft.Quantum.Environment.GetQubitsAvailableToUse
summary: Te funkcje dostarczają informacji o środowisku, w którym występuje obliczenie Quantum.
uid: Microsoft.Quantum.Environment
metadata:
  ms.openlocfilehash: 87e1659f8ecdd6df99271f7552f683ffed85b151
  ms.sourcegitcommit: a87c1aa8e7453360025e47ba614f25b02ea84ec3
  ms.translationtype: MT
  ms.contentlocale: pl-PL
  ms.lasthandoff: 11/26/2020
  ms.locfileid: "96201448"
