### YamlMime:QSharpNamespace
uid: microsoft.quantum.environment
name: Microsoft.Quantum.Environment
summary: " # <a name=\"summary\"></a>Podsumowanie\n Te funkcje dostarczają informacji o środowisku, w którym występuje obliczenie Quantum."
operations:
- uid: microsoft.quantum.environment.getqubitsavailabletoborrow
  summary: >-
    Zwraca liczbę qubits, które są obecnie dostępne do zażyczania.

    Obejmuje to nieużywane qubits; oznacza to, że obejmuje to qubits zwrócone przez `GetQubitsAvailableToUse`.
- uid: microsoft.quantum.environment.getqubitsavailabletouse
  summary: Zwraca liczbę qubits, która jest obecnie dostępna do użycia.
metadata:
  ms.openlocfilehash: bd6d442aabb179f4c5fea0a0f48efaa472ec00cf
  ms.sourcegitcommit: db23885adb7ff76cbf8bd1160d401a4f0471e549
  ms.translationtype: MT
  ms.contentlocale: pl-PL
  ms.lasthandoff: 05/01/2020
  ms.locfileid: "82673346"
