### YamlMime:QSharpType
uid: microsoft.quantum.environment.getqubitsavailabletouse
name: GetQubitsAvailableToUse
type: operation
namespace: microsoft.quantum.environment
summary: Zwraca liczbę qubits, która jest obecnie dostępna do użycia.
syntax: 'operation GetQubitsAvailableToUse () : Int'
input:
  content: ()
  types: []
output:
  content: Int
  types:
  - summary: >-
      Liczba qubits, które mogą zostać przydzieloną w `using` instrukcji.

      Jeśli używana maszyna docelowa nie dostarcza tych informacji, `-1` zostanie zwrócona wartość.
    isPrimitive: true
    uid: Int
seeAlso:
- getqubitsavailabletoborrow
metadata:
  ms.openlocfilehash: 326195ba3fa7b880d9b6871d16ea7a12c1c9a2ea
  ms.sourcegitcommit: 685a8ab16d7e6a25e63a168d6e7c385fa6e876cc
  ms.translationtype: MT
  ms.contentlocale: pl-PL
  ms.lasthandoff: 09/29/2020
  ms.locfileid: "91484737"
