### YamlMime:QSharpType
uid: microsoft.quantum.environment.getqubitsavailabletoborrow
name: GetQubitsAvailableToBorrow
type: operation
namespace: Microsoft.Quantum.Environment
summary: >-
  Zwraca liczbę qubits, które są obecnie dostępne do zażyczania.

  Obejmuje to nieużywane qubits; oznacza to, że obejmuje to qubits zwrócone przez `GetQubitsAvailableToUse`.
syntax: 'operation GetQubitsAvailableToBorrow () : Int'
input:
  content: ()
  types: []
output:
  content: Int
  types:
  - summary: >-
      Liczba qubits, które mogą zostać przydzieloną w instrukcji `borrowing`.

      Jeśli używana maszyna docelowa nie zawiera tych informacji, zostanie zwrócona `-1`.
    isPrimitive: true
    uid: Int
seeAlso:
- getqubitsavailabletouse
metadata:
  ms.openlocfilehash: c0caf866ad9a8773aa11ee7c6951ca3acc60cbaa
  ms.sourcegitcommit: edcf15044d7bdf4f8b21fb8f6af4bde475eb13a0
  ms.translationtype: MT
  ms.contentlocale: pl-PL
  ms.lasthandoff: 11/05/2019
  ms.locfileid: "73230487"
