### YamlMime:QSharpType
uid: microsoft.quantum.environment.getqubitsavailabletouse
name: GetQubitsAvailableToUse
type: operation
namespace: Microsoft.Quantum.Environment
summary: Zwraca liczbę qubits, która jest obecnie dostępna do użycia.
syntax: 'operation GetQubitsAvailableToUse () : Int'
input:
  content: ()
  types: []
output:
  content: Int
  types:
  - summary: >-
      Liczba qubits, które mogą zostać przydzieloną w instrukcji `using`.

      Jeśli używana maszyna docelowa nie zawiera tych informacji, zostanie zwrócona `-1`.
    isPrimitive: true
    uid: Int
seeAlso:
- getqubitsavailabletoborrow
ms.openlocfilehash: 1cb1331aa26ec9755a9e379336f46387b61bb0ae
ms.sourcegitcommit: 8becfb03eb60ba205c670a634ff4daa8071bcd06
ms.translationtype: MT
ms.contentlocale: pl-PL
ms.lasthandoff: 10/31/2019
ms.locfileid: "73230470"
