### YamlMime:QSharpType
uid: microsoft.quantum.chemistry.jordanwigner.preparesparsemulticonfigurationalstate
name: PrepareSparseMultiConfigurationalState
type: operation
namespace: microsoft.quantum.chemistry.jordanwigner
summary: Rozrzedzony proces wielokonfiguracyjnego stanu wersji próbnej przez dodanie excitations do wstępnego stanu wersji próbnej.
syntax: 'operation PrepareSparseMultiConfigurationalState (initialStatePreparation : (Qubit[] => Unit), excitations : Microsoft.Quantum.Chemistry.JordanWigner.JordanWignerInputState[], qubits : Qubit[]) : Unit'
input:
  content: '(initialStatePreparation : (Qubit[] => Unit), excitations : Microsoft.Quantum.Chemistry.JordanWigner.JordanWignerInputState[], qubits : Qubit[])'
  types:
  - name: initialStatePreparation
    summary: Jednostka przygotowana do przygotowania wstępnego stanu wersji próbnej.
    isOperation: true
    input:
      types:
      - isArray: true
        isPrimitive: true
        uid: Qubit
    output:
      types:
      - isPrimitive: true
        uid: Unit
  - name: excitations
    summary: Excitations stanu wstępnej wersji próbnej reprezentowane przez amplitudę wzbudzania i indeksów qubit.
    isArray: true
    uid: microsoft.quantum.chemistry.jordanwigner.jordanwignerinputstate
  - name: qubits
    summary: Qubits hamiltonian.
    isArray: true
    isPrimitive: true
    uid: Qubit
output:
  content: Unit
  types:
  - isPrimitive: true
    uid: Unit
metadata:
  ms.openlocfilehash: cb4a90a4686c26139f956ae7438fd1da6b38897b
  ms.sourcegitcommit: d6ac6f4345be0dd68f1bcd944f44b08e7a3cf346
  ms.translationtype: MT
  ms.contentlocale: pl-PL
  ms.lasthandoff: 09/02/2020
  ms.locfileid: "89339307"
