### YamlMime:QSharpType
uid: microsoft.quantum.environment.getqubitsavailabletoborrow
name: GetQubitsAvailableToBorrow
type: operation
namespace: Microsoft.Quantum.Environment
summary: >-
  Zwraca liczbę qubits, które są obecnie dostępne do zażyczania.

  Obejmuje to nieużywane qubits; oznacza to, że obejmuje to qubits zwrócone przez `GetQubitsAvailableToUse`.
syntax: 'operation GetQubitsAvailableToBorrow () : Int'
input:
  content: ()
  types: []
output:
  content: Int
  types:
  - summary: >-
      Liczba qubits, które mogą zostać przydzieloną w `borrowing` instrukcji.

      Jeśli używana maszyna docelowa nie dostarcza tych informacji, `-1` zostanie zwrócona wartość.
    isPrimitive: true
    uid: Int
seeAlso:
- getqubitsavailabletouse
metadata:
  ms.openlocfilehash: 99dd2afb66c334b112a2ee511b0437281da6b888
  ms.sourcegitcommit: db23885adb7ff76cbf8bd1160d401a4f0471e549
  ms.translationtype: MT
  ms.contentlocale: pl-PL
  ms.lasthandoff: 05/01/2020
  ms.locfileid: "82682409"
